---
AWSTemplateFormatVersion: "2010-09-09"

Description: This Template creates autoscaling group

Metadata:

Parameters:
  ImageId:
    Type: String
    Default: ami-0d7a109bf30624c99
    AllowedValues:
      - ami-0d7a109bf30624c99
      - ami-0873bd33f11079049
      - ami-080e1f13689e07408
      - ami-0f9c44e98edf38a2b
      - ami-0fe630eb857a6ec83

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.nano
    Description: Enter t2.micro, t2.nano. Default is t2.micro.

Resources:
  WebServerLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      LaunchConfigurationName: WebServerConfiguration
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Use this for your user data (script from top to bottom)
          # install httpd (Linux 2 version)
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello World from Our Website</h1>" > /var/www/html/index.html

  WebServerAutoscalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName:
      AvailabilityZones: !GetAZs ""
      LaunchConfigurationName: !Ref WebServerLaunchConfiguration
      MaxSize: 0
      MinSize: 0
      Tags:
        - Key: keyname
          Value: value
          PropagateAtLaunch: True|False
