---
- name: Install and Start nginx
  hosts: web
  become: true

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: Start nginx and ensure it is running
      service:
        name: nginx
        state: started
